const data = {
    products: [
        {
            id: 22,
            item_name: 'Sardine Cans',
            slug: 'sardine cans',
            type: 'delicious fish',
            image: 'https://m.media-amazon.com/images/I/81A9tHLuPoL.jpg',
            price: 5,
            quantity: 10,
            expiry_date: '10/12/2022',
            brand: 'Ayam Brand',
            description: 'delicious',
        },
        {
            id: 24,
            item_name: 'Carrots - 5pc',
            slug: 'carrots',
            type: 'Vegetable',
            image: '/images/Carrots.jpg',
            price: 1.50,
            quantity: 1,
            expiry_date: '20-10-2022',
            brand: 'Fairprice',
            description: 'crunchy',
        },
        {
            id: 3,
            item_name: 'Gardenia Wholemeal Bread - Fine Grain',
            slug: 'gardenia wholemeal bread - fine grain',
            type: 'Bread',
            image: '/images/Gardenia Wholemeal Bread.jpg',
            price: 1.50,
            quantity: 5,
            expiry_date: '20-10-2022',
            brand: 'Gardenia',
            description: 'like bread',
        },
        {
            id: 4,
            item_name: 'Baked Beans',
            slug: 'baked beans',
            type: 'Canned Food',
            image: '/images/Baked Beans.jpg',
            price: 0.70,
            quantity: 2,
            expiry_date: '25-10-2022',
            brand: 'Ayam Brand',
            description: 'beanss',
        },
    ],
};

export default data;